#!/bin/bash

cd collatz/app/bin/main/

echo "Reminder to build the software beforehand! -> ./build"
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "What number do you want to run the calculator through?"
read number

echo "Ok, running the calculator..."
echo
java collatz.App $number