#!/bin/bash

echo "Reminder to build the software beforehand! -> ./build"
echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
echo "What number do you want to run the calculator through?"
read number

echo "Ok, running the calculator..."
echo

cd collatz/app/build/classes/java/main/
java collatz.App $number